version: "3"
services:
  mongo:
    image: mongo:3.5
    ports:
      - 27017:27017

  pritunl:
    image: pritunl:latest
    ports:
      - 8080:80
      - 4443:443
    links:
    - mongo
    environment:
    - MONGODB_URI=mongodb://mongo:27017/pritunl
    - PRITUNL_REVERSE_PROXY=false
    - PRITUNL_SERVER_SSL=true
    - PRITUNL_SERVER_PORT=443